Attribute VB_Name = "ErrorLogChecker"
'~~> Change this to the relevant path
Const strPath As String = "C:\temp\errorlog\"
Const SoakRoomTemp As Integer = 50

    Type ResultType
        Error As String
        Date As String
        Temperature As String
    End Type
    
Sub ParseTextFiles()

'
' Read Output Voltage from results files generated by the Exordia
'
'
    Dim ws As Worksheet
    Dim MyData As String, strData() As String
    Dim txtLine() As String
    Dim WriteToRow As Long, i As Long
    Dim strCurrentTxtFile As String
    Dim Found As Boolean

    Dim Result(999) As ResultType
    
    Found = False
    
    strCurrentTxtFile = Dir(strPath & "*.csv")

    '~~> Looping through all text files in a folder
    Do While strCurrentTxtFile <> ""

        '~~> Open the file in 1 go to read it into an array
        Open strPath & strCurrentTxtFile For Binary As #1
        MyData = Space$(LOF(1))
        Get #1, , MyData
        Close #1

        strData() = Split(MyData, vbCrLf)
        
        j = 0
        
        For i = LBound(strData) To UBound(strData) - 1
            txtLine() = Split(strData(i), ",")
            TempError = txtLine(1)
            TempTemperature = txtLine(5)  'Split(txtLine(5), "C")
            If TempError <> "9" And Val(TempTemperature) > SoakRoomTemp Then
                j = j + 1
                Result(j).Error = txtLine(1)
                Result(j).Date = txtLine(4)
                Result(j).Temperature = txtLine(5)
                Debug.Print Result(j).Date, Result(j).Error, Result(j).Temperature
                Found = True
            End If
        Next i
    
        If j > 0 Then
            DisplayMessage = "Date : Error : Temperature"
            For i = 1 To j
                LineText = Result(i).Date & " : " & Result(i).Error & " : " & Result(i).Temperature
                DisplayMessage = DisplayMessage & vbLf & LineText
            Next i
        Else
            'DisplayMessage = "No Soak Room Errors" ' Use this line to report that there are no errors.
            DisplayMessage = ""                     ' Use this line to avoid unnecessary mouse clicks.
        End If
        
        If DisplayMessage <> "" Then R = MsgBox(DisplayMessage, , strCurrentTxtFile)
        
    strCurrentTxtFile = Dir
    Loop

    If Not Found Then MsgBox ("No Soak Room Errors")
    
End Sub
