Attribute VB_Name = "ParseTextFiles"
'~~> Change this to the relevant path
Const strPath As String = "C:\Temp\ET200 Zollner results\"

Sub ParseTextFiles()

'
' Read Output Voltage from results files generated by the Exordia
'
'
    Dim ws As Worksheet
    Dim MyData As String, strData() As String
    Dim txtLine() As String
    Dim WriteToRow As Long, i As Long
    Dim strCurrentTxtFile As String

    Set ws = Sheets("Sheet1")
    strPath = "C:\Temp\ET200 Exordia\"

    '~~> Start from Row 1
    WriteToRow = 1

    strCurrentTxtFile = Dir(strPath & "*.Txt")

    '~~> Looping through all text files in a folder
    Do While strCurrentTxtFile <> ""

        '~~> Open the file in 1 go to read it into an array
        Open strPath & strCurrentTxtFile For Binary As #1
        MyData = Space$(LOF(1))
        Get #1, , MyData
        Close #1

        strData() = Split(MyData, vbCrLf)
        
        '~~> Read from the array and write to Excel
        For i = LBound(strData) To UBound(strData)
            If InStr(strData(i), "Serial Number:") Then
                txtLine = Split(strData(i), ":")
                serialNum = txtLine(1)
            End If
            If InStr(strData(i), "7 Output Test:") Then
                txtLine = Split(strData(i + 6), ":")
                txtLine(0) = serialNum  ' overwrite 1st entry with serial number
                WriteToCol = 1
                For j = LBound(txtLine) To UBound(txtLine)
                    If txtLine(j) <> "" Then
                        ws.Cells(WriteToRow, WriteToCol).Value = txtLine(j)
                        WriteToCol = WriteToCol + 1
                    End If
                Next j
                
            End If
        Next i
        
        WriteToRow = WriteToRow + 1
        strCurrentTxtFile = Dir
    Loop

    MsgBox "Done"
End Sub
